---
- name: Add EPEL repository.
  shell: yum install -y epel-release

- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Update Pip
  shell: pip install pip -U -i https://pypi.douban.com/simple

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ 'pip3' if pip_package == 'python3-pip' else 'pip' }}"
  with_items: "{{ pip_install_packages }}"
